Fixed a couple of typos
treffynnon/sqlstyle.guide pull request #71
Opened 2020-08-23 14:45 UTC by robertopauletto

2020-08-23 16:55 UTC, szepeviktor approved these changes

2020-08-24 03:56 UTC, treffynnon requested changes

2020-08-24 03:56 UTC, treffynnon commented on .gitignore
> +.vscode/
Please don't include this change as it is for a particular editor, but rather add it to your global git ignore instead: https://anthonygharvey.com/productivity/how_to_create_a_global_gitignore_file

2020-08-27 22:39 UTC, merged

2020-08-27 22:43 UTC, treffynnon commented
Thanks for the fixes. If you need to make further changes please update your fork with the latest changes from here first. I have moved the main `sqlstyle.guide.it.md` into the `_include` folder alongside all the other translations.